export { HomePage } from './home/view/HomePage';
export { NotFoundPage } from './notFound/view/NotFoundPage';
export { ProductPage } from './product/view/ProductPage';
export { CartPage } from './cart/view/CartPage';
export { FavoritePage } from './favorite/view/FavoritePage';
export { CatalogPage } from './catalog/view/CatalogPage';
export { AboutUsPage } from './aboutUs/view/AboutUsPage';
export { RegistrationPage } from './registration/view/RegistrationPage';
export { LoginPage } from './login/view/LoginPage';
